language: rust
rust:
  - nightly
  - beta
  - stable
before_script:
  - rustup component add clippy
script:
  - cargo test
  - cd executors
  - ./test-features.sh

matrix:
  allow_failures:
    - rust: nightly
