os: linux
dist: xenial
language: rust
rust:
  - nightly
  - beta
  - stable
before_script:
  - rustup component add clippy
script:
  - cargo test
  - cd executors
  - ./test-features.sh

jobs:
  include:
    stage: coverage
    name: "Test Coverage"
    before_install:
      - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
    rust: nightly
    script:
      - export CARGO_INCREMENTAL=0
      - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off"
      - cargo build --verbose $CARGO_OPTIONS
      - cargo test --verbose $CARGO_OPTIONS
      - cd executors
      - ./test-features.sh
      - cd ..
      - |
        zip -0 ccov.zip `find . \( -name "executors*.gc*" \) -print`;
        ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
        bash <(curl -s https://codecov.io/bash) -f lcov.info;
