[package]
name = "crossbeam-channel-pool"
version = "0.1.0"
authors = ["Lars Kroll <lkroll@kth.se>"]

[dependencies]
utils = { path = "../utils/" }
crossbeam-channel = "0.1.1"
log = "0.3"
synchronoise = "0.4.0"

[dev-dependencies]
env_logger = "0.4"
